<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema
    xmlns="http://purl.org/dc/terms/"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://purl.org/dc/terms/"
    dc:title="Selected Dublin Core types and attributes"
    dc:creator="https://github.com/rv1971"
    dc:created="2017-01-01"
    dc:modified="2026-08-18"
    xml:lang="en">
  <xsd:annotation>
    <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
      <h2>About</h2>

      <p>This schema document describes selected <a
      href="http://purl.org/dc/terms/">Dublin Core</a> related types
      and attributes. Its main purpose is to re-use the semantics
      defined there, so the definitions are copied almost
      verbatim.</p>
    </xsd:documentation>
  </xsd:annotation>

  <xsd:import
      namespace="http://www.w3.org/2000/01/rdf-schema#"
      schemaLocation="rdfs.xsd"/>

  <xsd:annotation>
    <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
      <h2>Simple types</h2>
    </xsd:documentation>
  </xsd:annotation>

  <xsd:simpleType name="Agent" id="Agent">
    <xsd:annotation>
      <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>A resource that acts or has the power to act.</p>

        <p>Examples of Agent include person, organization, and
        software agent.</p>
      </xsd:documentation>
    </xsd:annotation>

    <xsd:restriction base="xsd:string"/>
  </xsd:simpleType>

  <xsd:simpleType name="AgentClass" id="AgentClass">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>A group of agents.</p>

        <p>Examples of Agent Class include groups seen as classes,
        such as students, women, charities, lecturers.</p>
      </xsd:documentation>
    </xsd:annotation>

    <xsd:restriction base="xsd:string"/>
  </xsd:simpleType>

  <xsd:simpleType name="Audience" id="Audience">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>This type does not impose further restrictions onto
        <code>AgentClass</code>. It is provided to allow further
        restriction via <code>&lt;xsd:redefine></code> and to support
        code which make use of XSD type information.</p>
      </xsd:documentation>
    </xsd:annotation>

    <xsd:restriction base="AgentClass"/>
  </xsd:simpleType>

  <xsd:simpleType name="RightsStatement" id="RightsStatement">
    <xsd:annotation>
      <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>A statement about the intellectual property rights (IPR)
        held in or over a resource, a legal document giving official
        permission to do something with a resource, or a statement
        about access rights.</p>
      </xsd:documentation>
    </xsd:annotation>

    <xsd:restriction base="xsd:string"/>
  </xsd:simpleType>

  <xsd:simpleType name="W3cdtf" id="W3cdtf">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p><a href="https://www.w3.org/TR/NOTE-datetime">W3C Date and
        Time Formats.</a></p>
      </xsd:documentation>
    </xsd:annotation>

    <xsd:union memberTypes="xsd:date xsd:dateTime"/>
  </xsd:simpleType>

  <xsd:simpleType name="Type" id="Type">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p><a href="https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#section-7">DCMI Type Vocabulary.</a></p>
      </xsd:documentation>
    </xsd:annotation>

    <xsd:restriction base="xsd:NCName">
      <xsd:enumeration value="Collection" id="Collection">
        <xsd:annotation>
         <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
            <p>An aggregation of resources.</p>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>

      <xsd:enumeration value="Dataset" id="Dataset">
        <xsd:annotation>
         <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
            <p>Data encoded in a defined structure.</p>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>

      <xsd:enumeration value="Event" id="Event">
        <xsd:annotation>
         <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
            <p>A non-persistent, time-based occurrence.</p>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>

      <xsd:enumeration value="Image" id="Image">
        <xsd:annotation>
         <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
            <p>A visual representation other than text.</p>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>

      <xsd:enumeration value="InteractiveResource" id="InteractiveResource">
        <xsd:annotation>
         <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
            <p>A resource requiring interaction from the user to be
            understood, executed, or experienced.</p>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>

      <xsd:enumeration value="MovingImage" id="MovingImage">
        <xsd:annotation>
         <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
            <p>A series of visual representations imparting an
            impression of motion when shown in succession.</p>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>

      <xsd:enumeration value="PhysicalObject" id="PhysicalObject">
        <xsd:annotation>
         <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
            <p>An inanimate, three-dimensional object or substance.</p>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>

      <xsd:enumeration value="Service" id="Service">
        <xsd:annotation>
         <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
            <p>A system that provides one or more functions.</p>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>

      <xsd:enumeration value="Software" id="Software">
        <xsd:annotation>
         <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
            <p>A computer program in source or compiled form.</p>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>

      <xsd:enumeration value="Sound" id="Sound">
        <xsd:annotation>
         <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
            <p>A resource primarily intended to be heard.</p>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>

      <xsd:enumeration value="StillImage" id="StillImage">
        <xsd:annotation>
         <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
            <p>A static visual representation.</p>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>

      <xsd:enumeration value="Text" id="Text">
        <xsd:annotation>
         <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
            <p>A resource consisting primarily of words for reading.</p>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:annotation>
    <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
      <h2>Attributes</h2>
    </xsd:documentation>
  </xsd:annotation>

  <xsd:attribute
      name="accessRights"
      type="RightsStatement"
      rdfs:label="Access Rights">
    <xsd:annotation>
      <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>Information about who access the resource or an indication
        of its security status.</p>

        <p>Access Rights may include information regarding access or
        restrictions based on privacy, security, or other
        policies.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:attribute>

  <xsd:attribute name="alternative" rdfs:label="Alternative title">
    <xsd:annotation xmlns="http://www.w3.org/1999/xhtml">
      <xsd:documentation>
        <p>An alternative name for the resource.</p>
      </xsd:documentation>
    </xsd:annotation>

    <xsd:simpleType>
      <xsd:restriction base="rdfs:Literal">
        <xsd:minLength value="1"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:attribute>

  <xsd:attribute name="audience" type="Audience" rdfs:label="Audience">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>A class of entity for whom the resource is intended or
        useful.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:attribute>

  <xsd:attribute name="created" type="W3cdtf" rdfs:label="Date created">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>Date of creation of the resource.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:attribute>

  <xsd:attribute name="creator" type="Agent" rdfs:label="Creator">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>An entity primarily responsible for making the
        resource.</p>

        <p>Examples of a Creator include a person, an organization, or
        a service.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:attribute>

  <xsd:attribute name="dateAccepted" type="W3cdtf" rdfs:label="Date accepted">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>Date of acceptance of the resource.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:attribute>

  <xsd:attribute name="identifier" rdfs:label="Identifier">
    <xsd:annotation>
      <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>An unambiguous reference to the resource within a given context.</p>
      </xsd:documentation>
    </xsd:annotation>

    <xsd:simpleType>
      <xsd:restriction base="rdfs:Literal">
        <xsd:minLength value="1"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:attribute>

  <xsd:attribute name="language" type="xsd:language-x" rdfs:label="Language">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>A language of the resource.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:attribute>

  <xsd:attribute name="modified" type="W3cdtf" rdfs:label="Date modified">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>Date on which the resource was changed.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:attribute>

  <xsd:attribute name="publisher" type="Agent" rdfs:label="Publisher">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>An entity responsible for making the resource
        available.</p>

        <p>Examples of a Publisher include a person, an organization,
        or a service.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:attribute>

  <xsd:attribute name="requires" type="xsd:anyURI" rdfs:label="Requires">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>A related resource that is required by the described
        resource to support its function, delivery, or coherence.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:attribute>

  <xsd:attribute name="rightsHolder" type="Agent" rdfs:label="Rights Holder">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>A person or organization owning or managing rights over the
        resource.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:attribute>

  <xsd:attribute name="title" rdfs:label="Title">
    <xsd:annotation>
      <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>A name given to the resource.</p>
      </xsd:documentation>
    </xsd:annotation>

    <xsd:simpleType>
      <xsd:restriction base="rdfs:Literal">
        <xsd:minLength value="1"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:attribute>

  <xsd:attribute name="source" type="xsd:anyURI" rdfs:label="Source">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>A related resource from which the described resource is derived.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:attribute>

  <xsd:attribute name="type" type="Type" rdfs:label="Type">
    <xsd:annotation>
     <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>The nature or genre of the resource.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:attribute>

  <xsd:annotation>
    <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
      <h2>Elements</h2>
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element
      name="alternative"
      id="alternative"
      rdfs:label="Alternative title">
    <xsd:annotation>
      <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>An alternative name for the resource.</p>
      </xsd:documentation>
    </xsd:annotation>

    <xsd:simpleType>
      <xsd:restriction base="rdfs:Literal">
        <xsd:minLength value="1"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>

  <xsd:element
      name="created"
      id="created"
      type="W3cdtf"
      rdfs:label="Date created">
    <xsd:annotation>
      <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>Date of creation of the resource.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:element>

  <xsd:element
      name="modified"
      id="modified"
      type="W3cdtf"
      rdfs:label="Date modified">
    <xsd:annotation>
      <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>Date on which the resource was changed.</p>
      </xsd:documentation>
    </xsd:annotation>
  </xsd:element>
</xsd:schema>
